project:
  type: website
  output-dir: docs

website:
  favicon: images/favico.ico
  title: "Junyi Chu"
  site-url: https://jchu10.github.io
  description: "Junyi Chu Academic Site"
  twitter-card: 
    creator: "@junyichu"

  repo-url: https://github.com/jchu10/jchu10.github.io
  repo-actions: [edit]

  navbar:
    right:
      - text: Home
        href: index.qmd
      - publications.qmd
      - cv.qmd
      - text: Get in touch!
        menu: 
          - icon: calendar
            text: Office hours
            href: https://calendar.app.google/Fj5gMEjnJcAEeE4i8
            target: _blank
          - icon: twitter
            text: Twitter
            href: https://twitter.com/junyichu
            target: _blank
          - icon: envelope
            text: Email
            href: mailto:junyichu10@gmail.com
          
  bread-crumbs: false

  page-footer: 
    right: "Built with ❤️ and [Quarto](https://quarto.org/)"
    background: dark
  
format:
  html:
    theme: 
      - simplex
      - styles.scss
    highlight-style: a11y-dark
    toc: false